name: C/C++ CI

on:
  push:
    branches: [ "actions" ]
  pull_request:
    branches: [ "actions" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      
    - uses: actions/checkout@v3
    - name: premake
      run: cmd /c "PREMAKE.bat"
    - uses: actions/checkout@v3
    - name: build
      run: dir
