name: C/C++ CI

on:
  push:
    branches: [ "actions" ]
  pull_request:
    branches: [ "actions" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: premake
    shell: cmd
    run: PREMAKE.bat
